# Generated by Django 3.1.7 on 2021-03-17 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('species', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=255)),
                ('chip_number', models.CharField(blank=True, default='', max_length=255)),
                ('passport_number', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
