# Generated by Django 3.1.7 on 2021-03-17 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_petownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(through='pets.PetOwnership', to=settings.AUTH_USER_MODEL),
        ),
    ]
